default:
  binance_api_key: !expr Sys.getenv("BINANCE_API_KEY")
  binance_api_secret: !expr Sys.getenv("BINANCE_API_SECRET")
spot:
  base_url: "https://api.binance.com"
  docs: "https://binance-docs.github.io/apidocs/spot/en/#market-data-endpoints"
  endpoints:
    ping: "/api/v3/ping"
    time: "/api/v3/time"
    exchange_info: "/api/v3/exchangeInfo"
    depth: "/api/v3/depth"
    trades: "/api/v3/trades"
    historical_trades: "/api/v3/historicalTrades"
    aggregate_trades: "/api/v3/aggTrades"
    klines: "/api/v3/klines"
    ui_klines: "/api/v3/uiKlines"
    avg_price: "/api/v3/avgPrice"
    ticker: "/api/v3/ticker"
    ticker_24hr: "/api/v3/ticker/24hr"
    ticker_trading_day: "/api/v3/ticker/tradingDay"
    ticker_price: "/api/v3/ticker/price"
    ticker_book: "/api/v3/ticker/bookTicker"
spot_test:
  base_url: "https://testnet.binance.vision"
  docs: "https://binance-docs.github.io/apidocs/spot/en/#market-data-endpoints"
  endpoints:
    ping: "/api/v3/ping"
    time: "/api/v3/time"
    exchange_info: "/api/v3/exchangeInfo"
    depth: "/api/v3/depth"
    trades: "/api/v3/trades"
    historical_trades: "/api/v3/historicalTrades"
    aggregate_trades: "/api/v3/aggTrades"
    klines: "/api/v3/klines"
    ui_klines: "/api/v3/uiKlines"
    avg_price: "/api/v3/avgPrice"
    ticker: "/api/v3/ticker"
    ticker_24hr: "/api/v3/ticker/24hr"
    ticker_trading_day: "/api/v3/ticker/tradingDay"
    ticker_price: "/api/v3/ticker/price"
    ticker_book: "/api/v3/ticker/bookTicker"
futures_usdt_m:
  base_url: "https://fapi.binance.com"
  docs: "https://binance-docs.github.io/apidocs/futures/en/#market-data-endpoints"
  endpoints:
    ping: "/fapi/v1/ping"
    time: "/fapi/v1/time"
    exchange_info: "/fapi/v1/exchangeInfo"
    depth: "/fapi/v1/depth"
    trades: "/fapi/v1/trades"
    historical_trades: "/fapi/v1/historicalTrades"
    aggregate_trades: "/fapi/v1/aggTrades"
    klines: "/fapi/v1/klines"
    continuous_klines: "/fapi/v1/continuousKlines"
    index_price_klines: "/fapi/v1/indexPriceKlines"
    mark_price_klines: "/fapi/v1/markPriceKlines"
    premium_index_klines: "/fapi/v1/premiumIndexKlines"
    premium_index: "/fapi/v1/premiumIndex"
    funding_rate: "/fapi/v1/fundingRate"
    funding_info: "/fapi/v1/fundingInfo"
    ticker_24hr: "/fapi/v1/ticker/24hr"
    ticker_price: "/fapi/v1/ticker/price"
    ticker_price_v2: "/fapi/v2/ticker/price"
    ticker_book: "/fapi/v1/ticker/bookTicker"
    open_interest: "/fapi/v1/openInterest"
    delivery_price: "/futures/data/delivery-price"
    oi_stats: "/futures/data/openInterestHist"
    top_ls_ratio_accounts: "/futures/data/topLongShortAccountRatio"
    top_ls_ratio_positions: "/futures/data/topLongShortPositionRatio"
    ls_ratio: "/futures/data/globalLongShortAccountRatio"
    taker_buy_sell_volume: "/futures/data/takerlongshortRatio"
    basis: "/futures/data/basis"
    bltv_kline: "/fapi/v1/lvtKlines"
    index_info: "/fapi/v1/indexInfo"
    asset_index: "/fapi/v1/assetIndex"
    constituents: "/fapi/v1/constituents"
futures_usdt_m_test:
  base_url: "https://testnet.binancefuture.com"
  docs: "https://binance-docs.github.io/apidocs/futures/en/#market-data-endpoints"
  endpoints:
    ping: "/fapi/v1/ping"
    time: "/fapi/v1/time"
    exchange_info: "/fapi/v1/exchangeInfo"
    depth: "/fapi/v1/depth"
    trades: "/fapi/v1/trades"
    historical_trades: "/fapi/v1/historicalTrades"
    klines: "/fapi/v1/klines"
    ticker_24hr: "/fapi/v1/ticker/24hr"
    ticker_price: "/fapi/v1/ticker/price"
futures_coin_m:
  base_url: "https://dapi.binance.com"
  docs: "https://binance-docs.github.io/apidocs/delivery/en/#market-data-endpoints"
  endpoints:
    ping: "/dapi/v1/ping"
    time: "/dapi/v1/time"
    exchange_info: "/dapi/v1/exchangeInfo"
    depth: "/dapi/v1/depth"
    trades: "/dapi/v1/trades"
    historical_trades: "/dapi/v1/historicalTrades"
    aggregate_trades: "/dapi/v1/aggTrades"
    premium_index: "/dapi/v1/premiumIndex"
    funding_rate: "/dapi/v1/fundingRate"
    funding_info: "/dapi/v1/fundingInfo"
    klines: "/dapi/v1/klines"
    continuous_klines: "/dapi/v1/continuousKlines"
    index_price_klines: "/dapi/v1/indexPriceKlines"
    mark_price_klines: "/dapi/v1/markPriceKlines"
    premium_index_klines: "/dapi/v1/premiumIndexKlines"
    ticker_24hr: "/dapi/v1/ticker/24hr"
    ticker_price: "/dapi/v1/ticker/price"
    ticker_book: "/dapi/v1/ticker/bookTicker"
    constituents: "/dapi/v1/constituents"
    open_interest: "/dapi/v1/openInterest"
    delivery_price: "/futures/data/delivery-price"
    oi_stats: "/futures/data/openInterestHist"
    top_ls_ratio_accounts: "/futures/data/topLongShortAccountRatio"
    top_ls_ratio_positions: "/futures/data/topLongShortPositionRatio"
    ls_ratio: "/futures/data/globalLongShortAccountRatio"
    taker_buy_sell_volume: "/futures/data/takerBuySellVol"
    basis: "/futures/data/basis"
futures_coin_m_test:
  base_url: "https://testnet.binancefuture.com"
  docs: "https://binance-docs.github.io/apidocs/delivery/en/#market-data-endpoints"
  endpoints:
    ping: "/dapi/v1/ping"
    time: "/dapi/v1/time"
    exchange_info: "/dapi/v1/exchangeInfo"
    depth: "/dapi/v1/depth"
    trades: "/dapi/v1/trades"
    historical_trades: "/dapi/v1/historicalTrades"
    klines: "/dapi/v1/klines"
    ticker_24hr: "/dapi/v1/ticker/24hr"
    ticker_price: "/dapi/v1/ticker/price"
options:
  base_url: "https://eapi.binance.com"
  docs: "https://binance-docs.github.io/apidocs/voptions/en#market-data-endpoints"
  endpoints:
    ping: "/eapi/v1/ping"
    time: "/eapi/v1/time"
    exchange_info: "/eapi/v1/exchangeInfo"
    depth: "/eapi/v1/depth"
    trades: "/eapi/v1/trades"
    historical_trades: "/eapi/v1/historicalTrades"
    klines: "/eapi/v1/klines"
    ticker_24hr: "/eapi/v1/ticker"
    index: "/eapi/v1/index"
    mark: "/eapi/v1/mark"
    excerise_history: "/eapi/v1/exerciseHistory"
    open_interest: "/eapi/v1/openInterest"
